gcse_programming_project/gcse_programming_project/urls.py
from django.contrib import admin
from django.templatetags.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=static("profit_calculator/img/favicon.ico"), permanent=True
        ),
    ),
    path("", include("profit_calculator.urls")),
    path("admin/", admin.site.urls),
]

gcse_programming_project/profit_calculator/urls.py
from django.urls import path

from . import views

app_name = "profit_calculator"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("signup/", views.UserSignupView.as_view(), name="signup"),
    path(
        "change-password/",
        views.UserPasswordChangeView.as_view(),
        name="change_password",
    ),
    path("flightplans/", views.FlightPlanView.as_view(), name="flightplans"),
    path(
        "flightplans/create/",
        views.CreateFlightPlan.as_view(),
        name="create_flightplan",
    ),
    path(
        "flightplans/update/",
        views.UpdateFlightPlan.as_view(),
        name="update_flightplan",
    ),
    path(
        "flightplans/delete/",
        views.DeleteFlightPlan.as_view(),
        name="delete_flightplan",
    ),
    path("airport/", views.AirportView.as_view(), name="airport_details"),
    path("aircraft/", views.AircraftView.as_view(), name="aircraft_details"),
    path("pricing/", views.PricingView.as_view(), name="pricing_details"),
    path("profit/", views.ProfitView.as_view(), name="profit_information"),
    path("export/", views.ExportView.as_view(), name="export"),
]

gcse_programming_project/profit_calculator/views.py
import io

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers
from django.core.exceptions import PermissionDenied
from django.http import FileResponse, Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView

from .models import (Aircraft, AircraftPlan, Airport, AirportPlan, FlightPlan,
                     PricingPlan)


def context_processor(request):
    if "current_fp" in request.session:
        try:
            fp = get_current_flightplan(request)
            complete = fp.complete()
        except FlightPlan.DoesNotExist:
            complete = False
    else:
        complete = False
    return {"complete": complete, "breakpoint": settings.NAVBAR_BREAKPOINT}


def get_current_flightplan(request):
    return FlightPlan.objects.get(pk=request.session["current_fp"])


def get_user_flightplans(request):
    return FlightPlan.objects.filter(user=request.user).order_by(
        "-created", "save_name"
    )


class IndexView(TemplateView):
    template_name = "profit_calculator/misc/index.html"


class UserLoginView(LoginView):
    template_name = "profit_calculator/auth/login.html"
    error_message = "Username/password combination is invalid. Please try again."

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class UserLogoutView(LogoutView):
    success_message = "Logged out successfully."

    def get_next_page(self):
        messages.success(self.request, self.success_message)
        return super().get_next_page()


class UserSignupView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "profit_calculator/auth/signup.html"
    success_url = reverse_lazy("profit_calculator:login")
    success_message = "Account created successfully."


class UserPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    template_name = "profit_calculator/auth/change_password.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Password changed successfully."


class FlightPlanView(ListView):
    template_name = "profit_calculator/misc/flightplan_list.html"
    paginate_by = 5

    def get_queryset(self):
        return get_user_flightplans(self.request)

    def post(self, request):
        """Set session cookie with current flightplan."""
        request.session["current_fp"] = int(request.POST["selected-fp"])
        return JsonResponse({"success": True})


class CreateFlightPlan(View):
    success_url = reverse_lazy("profit_calculator:flightplans")

    def post(self, request):
        if len(self.request.POST["save-name"]) > 100:
            return self.form_invalid()
        else:
            return self.form_valid()

    def form_valid(self):
        if FlightPlan.objects.filter(user=self.request.user).count() >= 25:
            messages.error(
                "You already have 25 flightplans. This is the maximum "
                "allowed. Please delete at least one and then try again."
            )
            return redirect("profit_calculator:flightplans")
        else:
            fp = FlightPlan(
                save_name=self.request.POST["save-name"], user=self.request.user
            )
            fp.save()
            messages.success(
                self.request, f'Flight plan "{fp.save_name}" created successfully.'
            )
            return redirect(self.success_url)

    def form_invalid(self):
        messages.error(
            self.request,
            "The entered save name is invalid. "
            "Please try again with a different save name.",
        )
        return redirect("profit_calculator:flightplans")


class UpdateFlightPlan(SingleObjectMixin, View):
    success_url = reverse_lazy("profit_calculator:flightplans")

    def post(self, request):
        self.object = self.get_object()
        if len(self.request.POST["save-name"]) > 100:
            return self.form_invalid()
        else:
            return self.form_valid()

    def form_valid(self):
        self.object.save_name = self.request.POST["save-name"]
        self.object.save()
        messages.success(
            self.request,
            f'Flight plan "{self.object.save_name}" updated successfully.',
        )
        return redirect("profit_calculator:flightplans")

    def form_invalid(self):
        messages.error(
            self.request,
            "The entered save name is invalid. "
            "Please try again with a different save name.",
        )
        return redirect("profit_calculator:flightplans")

    def get_object(self, **kwargs):
        fp = get_object_or_404(FlightPlan, pk=self.request.POST["selected-fp"])
        if fp.user == self.request.user:
            return fp
        else:
            raise PermissionDenied(
                "You do not have permission to edit this flight plan."
            )


class DeleteFlightPlan(SingleObjectMixin, View):
    def post(self, request):
        self.object = self.get_object()
        self.object.delete()
        try:
            del request.session["current_fp"]
        except KeyError:
            pass
        messages.success(request, "Flight plan deleted successfully.")
        return redirect("profit_calculator:flightplans")

    def get_object(self, **kwargs):
        try:
            return get_object_or_404(FlightPlan, pk=self.request.POST["selected-fp"])
        except KeyError:
            raise Http404("Selected flightplan does not exist.")


class AirportView(SuccessMessageMixin, UpdateView):
    model = AirportPlan
    fields = ["uk_airport", "foreign_airport"]
    template_name = "profit_calculator/forms/airportplan_form.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Airport information submitted successfully."
    error_message = "The submitted airport information was invalid. Please try again."

    def get_object(self, **kwargs):
        fp = get_current_flightplan(self.request)
        return fp.airport_plan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["airports"] = Airport.objects.all()
        return context

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class AircraftView(SuccessMessageMixin, UpdateView):
    model = AircraftPlan
    fields = ["aircraft", "num_first_class"]
    template_name = "profit_calculator/forms/aircraftplan_form.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Aircraft information submitted successfully."
    error_message = "The submitted aircraft information was invalid. Please try again."

    def get_object(self, **kwargs):
        fp = get_current_flightplan(self.request)
        return fp.aircraft_plan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["aircrafts"] = Aircraft.objects.all()
        context["aircraft_values"] = {
            aircraft.pk: [aircraft.max_standard_class, aircraft.min_first_class]
            for aircraft in Aircraft.objects.all()
        }
        return context

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class PricingView(SuccessMessageMixin, UpdateView):
    model = PricingPlan
    fields = ["standard_class_price", "first_class_price"]
    template_name = "profit_calculator/forms/pricingplan_form.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Pricing information submitted successfully."
    error_message = "The submitted pricing information was invalid. Please try again."

    def get_object(self, **kwargs):
        fp = get_current_flightplan(self.request)
        return fp.pricing_plan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fp = get_current_flightplan(self.request)
        disable = False
        if not fp.airport_plan.details_exist():
            messages.error(
                self.request,
                mark_safe(
                    f"No airport data has been submitted. This is needed to "
                    f"calculate the profit. Press <a href='"
                    f"{reverse('profit_calculator:airport_details')}'>here</a> to "
                    f"enter it."
                ),
                "top",
            )
            disable = True
        if not fp.aircraft_plan.details_exist():
            messages.error(
                self.request,
                mark_safe(
                    f"No aircraft data has been submitted. This is needed to "
                    f"calculate the profit. Press <a href='"
                    f"{reverse('profit_calculator:aircraft_details')}'>here</a> to "
                    f"enter it."
                ),
                "top",
            )
            disable = True
        if not fp.aircraft_plan.in_range() and not disable:
            messages.error(
                self.request,
                mark_safe(
                    f"This route is longer than the range of the aircraft selected. "
                    f"Please change the aircraft <a href='"
                    f"{reverse('profit_calculator:aircraft_details')}'>here</a> or "

gcse_programming_project/profit_calculator/templates/profit_calculator/misc/export.html
{% extends "profit_calculator/base/standard_base.html" %}

{% block title %}Export data{% endblock %}
{% block header %}Export flightplan information{% endblock %}

{% block content %}
    <div class="container px-0 pt-3 pb-2 d-flex flex-column">
        <button class="btn btn-dark my-2 mb-0"  data-bs-toggle="collapse" data-bs-target="#export-form-container">Export data</button>
        <div class="collapse border border-top-0 rounded-bottom bg-light" id="export-form-container">
            <form class="px-5 py-3" method="post">
                {% csrf_token %}
                <div class="form-group my-2">
                    <span class="pb-1">File type:</span>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="filetype" id="json-file" value="json">
                        <label class="form-check-label" for="json-file">
                            JSON
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="filetype" id="xml-file" value="xml">
                        <label class="form-check-label" for="xml-file">
                            XML
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="filetype" id="yaml-file" value="yaml">
                        <label class="form-check-label" for="yaml-file">
                            YAML
                        </label>
                    </div>
                </div>
                <input type="hidden" name="import/export" value="export" />
                <input class="btn btn-dark mt-1 mb-2 btn-block" type="submit" value="Export"/>
            </form>
        </div>
        <a class="btn btn-dark mt-3" href="{% url 'profit_calculator:index' %}">Back to Main Menu</a>
    </div>
{% endblock %}

gcse_programming_project/profit_calculator/templates/profit_calculator/misc/flightplan_list.html
{% extends "profit_calculator/base/no_nav_base.html" %}

{% block title %}Manage flight plans{% endblock %}
{% block header %}Manage flight plans{% endblock %}

{% load static %}

{% block content %}
    <table class="table table-hover" id="flightplan-table">
        <thead>
            <tr>
                <th style="width: 65%" scope="col">Save name</th>
                <th style="width: 30%" scope="col">Created</th>
                <th style="width: 5%" scope="col">Complete</th>
            </tr>
        </thead>
        <tbody>
        {% if object_list %}
                {% for flightplan in page_obj %}
                <tr data-id="{{ flightplan.pk }}" tabindex="0">
                    <td>{{ flightplan.save_name }}</td>
                    <td>{{ flightplan.created }}</td>
                    {% if flightplan.complete %}
                        <td class="text-center p-1"><img src="{% static 'profit_calculator/img/tick.svg' %}" width="30" height="30" alt="Complete"></td>
                    {% else %}
                        <td class="text-center p-1"><img src="{% static 'profit_calculator/img/cross.svg' %}" width="30" height="30" alt="Not complete"></td>
                    {% endif %}
                </tr>
                {% endfor %}
        {% else %}
            <tr data-no-items="true">
                <td colspan="3" class="text-muted fw-light text-center fst-italic">No flightplans exist</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <button class="btn btn-dark mb-2" id="create-button" data-bs-toggle="modal" data-bs-target="#create-modal">Create</button>
    <button class="btn btn-danger float-end ms-1 mb-2" id="delete-button" data-bs-toggle="modal" data-bs-target="#delete-modal" disabled>Delete</button>
    <button class="btn btn-dark float-end ms-1 mb-2" id="edit-button" data-bs-toggle="modal" data-bs-target="#edit-modal" disabled>Edit</button>
    <button class="btn btn-dark float-end mb-2" id="select-button" disabled>Select</button>

    <div class="alert mt-2 d-none" id="error-message" role="alert"></div>

    <div class="modal" tabindex="-1" id="create-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create flight plan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'profit_calculator:create_flightplan' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="input-group">
                            <span class="input-group-text">Save name</span>
                            <input type="text" name="save-name" maxlength="100" class="form-control" id="create-save-name">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-dark" value="Create">
                        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="edit-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit flight plan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'profit_calculator:update_flightplan' %}">
                    {% csrf_token %}
                    <input type="hidden" name="selected-fp">
                    <div class="modal-body">
                        <div class="input-group">
                            <span class="input-group-text">Save name</span>
                            <input type="text" name="save-name" maxlength="100" class="form-control" id="edit-save-name">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-dark" value="Update">
                        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="delete-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete flight plan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'profit_calculator:delete_flightplan' %}">
                    {% csrf_token %}
                    <input type="hidden" name="selected-fp">
                    <div class="modal-body">
                        This will irreversibly delete the selected flight plan. Are you sure?
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-danger" value="Continue" id="confirm-delete">
                        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block under_message_content %}
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation" class="mt-3">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="?page=1" aria-label="First page">
                        <span aria-hidden="true">&Lang;</span>
                    </a>
                </li>
                <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"
                       aria-label="Previous">
                        <span aria-hidden="true">&lang;</span>
                    </a>
                </li>
                {% for page_number in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endfor %}
                <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}"
                       aria-label="Next">
                        <span aria-hidden="true">&rang;</span>
                    </a>
                </li>
                <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                    <a class="page-link" href="?page=last"
                       aria-label="Last page">
                        <span aria-hidden="true">&Rang;</span>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="container-fluid d-flex justify-content-center align-items-center">
            <span class="fw-light fst-italic text-muted text-center">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js" integrity="sha512-Meww2sXqNHxI1+5Dyh/9KAtvI9RZSA4c1K2k5iL02oiPO/RH3Q30L3M1albtqMg50u4gRTYdV4EXOQqXEI336A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (e) => {
            let table = document.querySelector('#flightplan-table');
            let tableRows = document.querySelectorAll('#flightplan-table tbody tr');

            let createButton = document.querySelector('#create-button');

            let selectButton = document.querySelector('#select-button');
            let editButton = document.querySelector('#edit-button');
            let deleteButton = document.querySelector('#delete-button');
            let rowButtons = [selectButton, editButton, deleteButton];

            let errorMessage = document.querySelector('#error-message');

            let selectedFpFields = document.querySelectorAll('input[name="selected-fp"]');
            let editNameField = document.querySelector('#edit-save-name');

            let selected;

            const csrftoken = Cookies.get('csrftoken');


            function showMessage (msgText, msgType) {
                errorMessage.textContent = msgText;
                errorMessage.classList = `alert alert-${msgType} mt-3`;
            }

            async function setFlightPlanCookie() {
                let data = new FormData();
                data.append("selected-fp", selected);
                await fetch('{% url 'profit_calculator:flightplans' %}', {
                    method: 'POST',
                    body: data,
                    headers: {
                        'X-CSRFToken': csrftoken
                    }
                })
                    .then(rawresponse => rawresponse.json())
                    .then(data => {
                        if (data.success){
                            window.location.href = "{% url 'profit_calculator:index' %}";
                        } else {
                            showMessage('Something went wrong. Please try again.', 'danger');
                        }
                    });
            }

            selectButton.addEventListener('click', (e) => {
                setFlightPlanCookie();
            });

            function handleTableRowClick(elem, event) {
                elem.parentNode.childNodes.forEach((sibElem) => {
                    if (sibElem.tagName == 'TR'){
                        sibElem.classList.remove('table-active');
                    }
                });
                elem.classList.add('table-active');
                selected = parseInt(elem.dataset.id);
                editNameField.value = elem.firstChild.nextSibling.textContent;
                selectedFpFields.forEach((field) => field.value = selected);
                rowButtons.forEach((button) => button.disabled = false);
            }

            tableRows.forEach((elem) => {
                if (!(elem.dataset.noItems == 'true')){
                    elem.addEventListener('click', (event) => {
                        handleTableRowClick(elem, event);
                    });
                    elem.addEventListener('dblclick', (event) => {
                        handleTableRowClick(elem, event);
                        setFlightPlanCookie();
                    });
                    elem.addEventListener('keyup', (event) => {
                        if (event.keyCode === 13) {
                            handleTableRowClick(elem, event);
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

gcse_programming_project/profit_calculator/templates/profit_calculator/misc/index.html
{% extends "profit_calculator/base/standard_base.html" %}

{% block title %}{% block header %}Home{% endblock %}{% endblock %}

{% block content %}
    <div class="mt-3 d-flex flex-column">
        <a href="{% url 'profit_calculator:flightplans' %}" class="btn btn-dark my-2">Manage flight plans</a>
        <hr class="m-2">
        <a href="{% url 'profit_calculator:airport_details' %}" class="btn btn-dark my-2">Enter airport details</a>
        <a href="{% url 'profit_calculator:aircraft_details' %}" class="btn btn-dark my-2">Enter aircraft details</a>
        <a href="{% url 'profit_calculator:pricing_details' %}" class="btn btn-dark my-2">Enter pricing details</a>
        <hr class="m-2">
        <a href="{% url 'profit_calculator:profit_information' %}" class="btn btn-dark my-2 {% if not complete %}disabled{% endif %}">Profit information</a>
        <hr class="m-2">
        <a href="{% url 'profit_calculator:export' %}" class="btn btn-dark my-2">Export flight plan information</a>
    </div>
{% endblock %}

gcse_programming_project/profit_calculator/templates/profit_calculator/misc/navbar.html
{% extends 'profit_calculator/base/base_navbar.html' %}


{% block nav %}
    {% url "profit_calculator:index" as index %}
    {% url "profit_calculator:airport_details" as airport_details %}
    {% url "profit_calculator:aircraft_details" as aircraft_details %}
    {% url "profit_calculator:pricing_details" as pricing_details %}
    {% url "profit_calculator:profit_information" as profit_information %}
    {% url "profit_calculator:clear_data" as clear_data %}
    {% url "profit_calculator:flightplans" as flightplans %}
    <ul class="navbar-nav mx-2 mx-{{ breakpoint }}-0">
        <li class="nav-item">
            <a class="nav-link {% if request.path == index %}active{% endif %}" href="{{ index }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.path == flightplans %}active{% endif %}" href="{{ flightplans }}">Manage flight plans</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.path == airport_details or request.path == aircraft_details or request.path == pricing_details %}active{% endif %}"
               href="#" id="navbar-forms-dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Data entry forms
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbar-forms-dropdown">
                <li><a class="dropdown-item {% if request.path == airport_details %}active{% endif %}"
                       href="{{ airport_details }}">Airport details</a></li>
                <li><a class="dropdown-item {% if request.path == aircraft_details %}active{% endif %}"
                       href="{{ aircraft_details }}">Aircraft details</a></li>
                <li><a class="dropdown-item {% if request.path == pricing_details %}active{% endif %}"
                       href="{{ pricing_details }}">Pricing details</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if not complete %}disabled{% elif request.path == profit_information %}active{% endif %}"
               href="{{ profit_information }}">Profit information</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'profit_calculator:export' %}">Export data</a>
        </li>
    </ul>
{% endblock %}