gcse_programming_project/gcse_programming_project/urls.py
from django.contrib import admin
from django.templatetags.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=static("profit_calculator/img/favicon.ico"), permanent=True
        ),
    ),
    path("", include("profit_calculator.urls")),
    path("admin/", admin.site.urls),
]

gcse_programming_project/profit_calculator/urls.py
from django.urls import path

from . import views

app_name = "profit_calculator"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("signup/", views.UserSignupView.as_view(), name="signup"),
    path(
        "change-password/",
        views.UserPasswordChangeView.as_view(),
        name="change_password",
    ),
    path("flightplans/", views.FlightPlanView.as_view(), name="flightplans"),
    path(
        "flightplans/create/",
        views.CreateFlightPlan.as_view(),
        name="create_flightplan",
    ),
    path(
        "flightplans/update/",
        views.UpdateFlightPlan.as_view(),
        name="update_flightplan",
    ),
    path(
        "flightplans/delete/",
        views.DeleteFlightPlan.as_view(),
        name="delete_flightplan",
    ),
    path("airport/", views.AirportView.as_view(), name="airport_details"),
    path("aircraft/", views.AircraftView.as_view(), name="aircraft_details"),
    path("pricing/", views.PricingView.as_view(), name="pricing_details"),
    path("profit/", views.ProfitView.as_view(), name="profit_information"),
    path("export/", views.ExportView.as_view(), name="export"),
]

gcse_programming_project/profit_calculator/views.py
import io

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers
from django.core.exceptions import PermissionDenied
from django.http import FileResponse, Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView

from .models import (Aircraft, AircraftPlan, Airport, AirportPlan, FlightPlan,
                     PricingPlan)


def context_processor(request):
    if "current_fp" in request.session:
        try:
            fp = get_current_flightplan(request)
            complete = fp.complete()
        except FlightPlan.DoesNotExist:
            complete = False
    else:
        complete = False
    return {"complete": complete, "breakpoint": settings.NAVBAR_BREAKPOINT}


def get_current_flightplan(request):
    return FlightPlan.objects.get(pk=request.session["current_fp"])


def get_user_flightplans(request):
    return FlightPlan.objects.filter(user=request.user).order_by(
        "-created", "save_name"
    )


class IndexView(TemplateView):
    template_name = "profit_calculator/misc/index.html"


class UserLoginView(LoginView):
    template_name = "profit_calculator/auth/login.html"
    error_message = "Username/password combination is invalid. Please try again."

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class UserLogoutView(LogoutView):
    success_message = "Logged out successfully."

    def get_next_page(self):
        messages.success(self.request, self.success_message)
        return super().get_next_page()


class UserSignupView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "profit_calculator/auth/signup.html"
    success_url = reverse_lazy("profit_calculator:login")
    success_message = "Account created successfully."


class UserPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    template_name = "profit_calculator/auth/change_password.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Password changed successfully."


class FlightPlanView(ListView):
    template_name = "profit_calculator/misc/flightplan_list.html"
    paginate_by = 5

    def get_queryset(self):
        return get_user_flightplans(self.request)

    def post(self, request):
        """Set session cookie with current flightplan."""
        request.session["current_fp"] = int(request.POST["selected-fp"])
        return JsonResponse({"success": True})


class CreateFlightPlan(View):
    success_url = reverse_lazy("profit_calculator:flightplans")

    def post(self, request):
        if len(self.request.POST["save-name"]) > 100:
            return self.form_invalid()
        else:
            return self.form_valid()

    def form_valid(self):
        if FlightPlan.objects.filter(user=self.request.user).count() >= 25:
            messages.error(
                "You already have 25 flightplans. This is the maximum "
                "allowed. Please delete at least one and then try again."
            )
            return redirect("profit_calculator:flightplans")
        else:
            fp = FlightPlan(
                save_name=self.request.POST["save-name"], user=self.request.user
            )
            fp.save()
            messages.success(
                self.request, f'Flight plan "{fp.save_name}" created successfully.'
            )
            return redirect(self.success_url)

    def form_invalid(self):
        messages.error(
            self.request,
            "The entered save name is invalid. "
            "Please try again with a different save name.",
        )
        return redirect("profit_calculator:flightplans")


class UpdateFlightPlan(SingleObjectMixin, View):
    success_url = reverse_lazy("profit_calculator:flightplans")

    def post(self, request):
        self.object = self.get_object()
        if len(self.request.POST["save-name"]) > 100:
            return self.form_invalid()
        else:
            return self.form_valid()

    def form_valid(self):
        self.object.save_name = self.request.POST["save-name"]
        self.object.save()
        messages.success(
            self.request,
            f'Flight plan "{self.object.save_name}" updated successfully.',
        )
        return redirect("profit_calculator:flightplans")

    def form_invalid(self):
        messages.error(
            self.request,
            "The entered save name is invalid. "
            "Please try again with a different save name.",
        )
        return redirect("profit_calculator:flightplans")

    def get_object(self, **kwargs):
        fp = get_object_or_404(FlightPlan, pk=self.request.POST["selected-fp"])
        if fp.user == self.request.user:
            return fp
        else:
            raise PermissionDenied(
                "You do not have permission to edit this flight plan."
            )


class DeleteFlightPlan(SingleObjectMixin, View):
    def post(self, request):
        self.object = self.get_object()
        self.object.delete()
        try:
            del request.session["current_fp"]
        except KeyError:
            pass
        messages.success(request, "Flight plan deleted successfully.")
        return redirect("profit_calculator:flightplans")

    def get_object(self, **kwargs):
        try:
            return get_object_or_404(FlightPlan, pk=self.request.POST["selected-fp"])
        except KeyError:
            raise Http404("Selected flightplan does not exist.")


class AirportView(SuccessMessageMixin, UpdateView):
    model = AirportPlan
    fields = ["uk_airport", "foreign_airport"]
    template_name = "profit_calculator/forms/airportplan_form.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Airport information submitted successfully."
    error_message = "The submitted airport information was invalid. Please try again."

    def get_object(self, **kwargs):
        fp = get_current_flightplan(self.request)
        return fp.airport_plan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["airports"] = Airport.objects.all()
        return context

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class AircraftView(SuccessMessageMixin, UpdateView):
    model = AircraftPlan
    fields = ["aircraft", "num_first_class"]
    template_name = "profit_calculator/forms/aircraftplan_form.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Aircraft information submitted successfully."
    error_message = "The submitted aircraft information was invalid. Please try again."

    def get_object(self, **kwargs):
        fp = get_current_flightplan(self.request)
        return fp.aircraft_plan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["aircrafts"] = Aircraft.objects.all()
        context["aircraft_values"] = {
            aircraft.pk: [aircraft.max_standard_class, aircraft.min_first_class]
            for aircraft in Aircraft.objects.all()
        }
        return context

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class PricingView(SuccessMessageMixin, UpdateView):
    model = PricingPlan
    fields = ["standard_class_price", "first_class_price"]
    template_name = "profit_calculator/forms/pricingplan_form.html"
    success_url = reverse_lazy("profit_calculator:index")
    success_message = "Pricing information submitted successfully."
    error_message = "The submitted pricing information was invalid. Please try again."

    def get_object(self, **kwargs):
        fp = get_current_flightplan(self.request)
        return fp.pricing_plan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fp = get_current_flightplan(self.request)
        disable = False
        if not fp.airport_plan.details_exist():
            messages.error(
                self.request,
                mark_safe(
                    f"No airport data has been submitted. This is needed to "
                    f"calculate the profit. Press <a href='"
                    f"{reverse('profit_calculator:airport_details')}'>here</a> to "
                    f"enter it."
                ),
                "top",
            )
            disable = True
        if not fp.aircraft_plan.details_exist():
            messages.error(
                self.request,
                mark_safe(
                    f"No aircraft data has been submitted. This is needed to "
                    f"calculate the profit. Press <a href='"
                    f"{reverse('profit_calculator:aircraft_details')}'>here</a> to "
                    f"enter it."
                ),
                "top",
            )
            disable = True
        if not fp.aircraft_plan.in_range() and not disable:
            messages.error(
                self.request,
                mark_safe(
                    f"This route is longer than the range of the aircraft selected. "
                    f"Please change the aircraft <a href='"
                    f"{reverse('profit_calculator:aircraft_details')}'>here</a> or "

gcse_programming_project/profit_calculator/templates/profit_calculator/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'profit_calculator/img/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

gcse_programming_project/profit_calculator/templates/profit_calculator/base/base_messages.html
{% extends 'profit_calculator/base/base.html' %}

{% block body %}
    <section class="content">
        {% block navbar %}{% endblock %}
        <main class="container p-3">
            {% for message in messages %}
                {% if "top" in message.extra_tags %}
                    <div class="alert {{ message.level_tag }}" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}

            {% block content %}{% endblock %}

            {% for message in messages %}
                {% if message.extra_tags != "top" %}
                    <div class="mt-2 alert {{ message.level_tag }}" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}

            {% block under_message_content %}{% endblock %}
        </main>
    </section>
{% endblock %}

gcse_programming_project/profit_calculator/templates/profit_calculator/base/base_navbar.html
{% load static %}

<header>
    <nav class="navbar navbar-expand-{{ breakpoint }} navbar-dark bg-dark px-2">
        <a class="navbar-brand" href="{% url 'profit_calculator:index' %}">
            <img src="{% static 'profit_calculator/img/plane.svg' %}" width="30" height="30" class="d-inline-block align-top mx-1" alt="Plane logo">
            Flight Plan Profitability Calculator
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapsed-section" aria-controls="navbar-collapsed-section" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapsed-section">
            {% block nav %}{% endblock %}
            <ul class="navbar-nav mx-2 ms-{{ breakpoint }}-auto me-{{ breakpoint }}-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbar-account-dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.is_authenticated %}{{ user.username }}{% else %}Account{% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbar-account-dropdown">
                        {% if user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'admin:app_list' app_label='profit_calculator' %}">Admin</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'profit_calculator:change_password' %}">Change password</a></li>
                        <li><a class="dropdown-item" href="{% url 'profit_calculator:logout' %}">Log out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

gcse_programming_project/profit_calculator/templates/profit_calculator/base/navbar.html
{% load static %}

{% url "profit_calculator:index" as index %}
{% url "profit_calculator:airport_details" as airport_details %}
{% url "profit_calculator:aircraft_details" as aircraft_details %}
{% url "profit_calculator:pricing_details" as pricing_details %}
{% url "profit_calculator:profit_information" as profit_information %}
{% url "profit_calculator:clear_data" as clear_data %}

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-2">
        <a class="navbar-brand" href="{% url 'profit_calculator:index' %}">
            <img src="{% static 'profit_calculator/img/plane.svg' %}" width="30" height="30" class="d-inline-block align-top mx-1" alt="Plane logo">
            Flight Plan Profitability Calculator
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapsed-section" aria-controls="navbar-collapsed-section" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapsed-section">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == index %}active{% endif %}" href="{{ index }}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path == airport_details or request.path == aircraft_details or request.path == pricing_details %}active{% endif %}" href="#" id="navbar-forms-dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Data entry forms
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbar-forms-dropdown">
                        <li><a class="dropdown-item {% if request.path == airport_details %}active{% endif %}" href="{{ airport_details }}">Airport details</a></li>
                        <li><a class="dropdown-item {% if request.path == aircraft_details %}active{% endif %}" href="{{ aircraft_details }}">Aircraft details</a></li>
                        <li><a class="dropdown-item {% if request.path == pricing_details %}active{% endif %}" href="{{ pricing_details }}">Pricing details</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if not complete %}disabled{% elif request.path == profit_information %}active{% endif %}" href="{{ profit_information }}">Profit information</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Import/export data</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == clear_data %}active{% endif %}" href="{{ clear_data }}">Clear data</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbar-account-dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.is_authenticated %}{{ user.username }}{% else %}Account{% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbar-account-dropdown">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'profit_calculator:logout' %}">Log out</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'profit_calculator:login' %}">Log in</a></li>
                            <li><a class="dropdown-item" href="{% url 'profit_calculator:signup' %}">Sign up</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

gcse_programming_project/profit_calculator/templates/profit_calculator/base/no_nav_base.html
{% extends 'profit_calculator/base/base_messages.html' %}

{% block body %}
    {% include 'profit_calculator/base/base_navbar.html' %}
    {{ block.super }}
{% endblock %}

gcse_programming_project/profit_calculator/templates/profit_calculator/base/standard_base.html
{% extends 'profit_calculator/base/base_messages.html' %}

{% block body %}
    {% include 'profit_calculator/misc/navbar.html' %}
    {{ block.super }}
{% endblock %}